groups:
- name: deployer
  jobs:
  - deploy
- name: self-update
  jobs:
  - self-update

resources:
  - name: tech-ops
    type: git
    source:
      uri: https://github.com/alphagov/tech-ops.git

  - name: govwifi-tech-docs
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-tech-docs.git"
      branch: master

jobs:
  - name: self-update
    serial: true
    plan:
    - get: tech-ops
      params:
        submodules: none
    - get: govwifi-tech-docs
      trigger: true
    - task: set-pipelines
      file: tech-ops/ci/tasks/self-updating-pipeline.yaml
      input_mapping: {repository: govwifi-tech-docs}
      params:
        CONCOURSE_TEAM: govwifi
        CONCOURSE_PASSWORD: ((readonly_local_user_password))
        PIPELINE_PATH: ci/pipelines/deploy.yml
        PIPELINE_NAME: tech-docs-deploy

  - name: deploy
    plan:
      - get: src
        resource: govwifi-tech-docs
        trigger: true

      - task: deploy
        params:
          CF_API: https://api.cloud.service.gov.uk
          CF_USER: ((govpaas-username))
          CF_PASS: ((govpaas-password))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
              tag: 50f6eb732334e0af7192bb884e558e3dc7e9fa33
          inputs:
            - name: src
          run:
            path: sh
            args:
              - -e
              - -c
              - |
                cd src/

                echo "Installing dependencies..."
                apk --update add g++ musl-dev make git nodejs
                bundle install

                echo "Running the build..."
                bundle exec middleman build

                echo "Logging into CF..."
                cf login -u "${CF_USER}" -p "${CF_PASS}" -a "${CF_API}" -s production

                echo "Pushing the app..."
                cf push govwifi-tech-docs
