# just a high level test to make sure everything builds properly. No actual tests.

groups:
- name: builder
  jobs:
  - build
- name: self-update
  jobs:
  - self-update

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: tech-ops
    type: git
    source:
      uri: https://github.com/alphagov/tech-ops.git

  - name: govwifi-tech-docs
    type: git
    source:
      uri: https://github.com/alphagov/govwifi-tech-docs.git

  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      repository: alphagov/govwifi-tech-docs
      access_token: ((github-access-token))

jobs:
  - name: self-update
    serial: true
    plan:
    - get: tech-ops
      params:
        submodules: none
    - get: govwifi-tech-docs
      trigger: true
    - task: set-pipelines
      file: tech-ops/ci/tasks/self-updating-pipeline.yaml
      input_mapping: {repository: govwifi-tech-docs}
      params:
        CONCOURSE_TEAM: govwifi
        CONCOURSE_PASSWORD: ((readonly_local_user_password))
        PIPELINE_PATH: ci/pipelines/pr.yml
        PIPELINE_NAME: tech-docs-pr

  - name: build
    interruptible: true
    disable_manual_trigger: true
    plan:
      - get: src
        resource: pull-request
        trigger: true
        version: every
      - <<: *update-status-pending

      - task: build
        privileged: true
        file: src/ci/tasks/build.yml

    on_failure:
      do:
        - <<: *update-status-failure
    on_success:
      do:
        - <<: *update-status-success


update-status-commands:
  update-status-base: &update-status-base
    put: update-status
    resource: pull-request
    get_params:
      skip_download: true

  update-status-params-base: &update-status-params-base
    path: src
    context: 'pr'

  update-status-pending: &update-status-pending
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: pending

  update-status-failure: &update-status-failure
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: failure

  update-status-success: &update-status-success
    <<: *update-status-base
    params:
      <<: *update-status-params-base
      status: success
